apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retail-mongodb-pvc
  namespace: vegetable-ns
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 3Gi
  storageClassName: retail-sc

