apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vegetable-mongodb
  namespace: vegetable-ns
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vegetable-config
                  key: MONGO_INITDB_DATABASE
 volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: vegetable-sc
        resources:
          requests:
            storage: 1Gi
